management:
#  server:
#    port: 9292
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
      show-components: always
    #show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: hello-actuator
    company: drumj

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true

